<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <RootNamespace>Itmo.ObjectOrientedProgramming.Lab5.Domain</RootNamespace>
    <AssemblyName>Itmo.ObjectOrientedProgramming.Lab5.Domain</AssemblyName>
  </PropertyGroup>

</Project>

